// Token sync build — Figma → DTCG → Style Dictionary → shadcn outputs.
// Generated/maintained by the token-sync step. Build artifacts in build/ are
// regenerated every run and must never be hand-edited (edit tokens in Figma).
import StyleDictionary from 'style-dictionary';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';

const PRIM = 'dtcg/primitives.json';
const DARK = 'dtcg/semantic.dark.json';
const LIGHT = 'dtcg/semantic.light.json';

// --- CSS + JSON for DARK (default = :root) ---
const sdDark = new StyleDictionary({
  source: [PRIM, DARK],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'build/css/',
      files: [{
        destination: '_root.css',
        format: 'css/variables',
        options: { outputReferences: true, selector: ':root' },
      }],
    },
    json: {
      transformGroup: 'js',
      buildPath: 'build/json/',
      files: [{ destination: 'dark.json', format: 'json/nested' }],
    },
  },
});

// --- CSS (semantic-only overrides) + JSON for LIGHT (.light) ---
const onlySemanticLight = (t) => t.filePath && t.filePath.includes('semantic.light');
const sdLight = new StyleDictionary({
  source: [PRIM, LIGHT],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'build/css/',
      files: [{
        destination: '_light.css',
        format: 'css/variables',
        options: { outputReferences: true, selector: '.light' },
        filter: onlySemanticLight,
      }],
    },
    json: {
      transformGroup: 'js',
      buildPath: 'build/json/',
      files: [{ destination: 'light.json', format: 'json/nested' }],
    },
  },
});

await sdDark.buildAllPlatforms();
await sdLight.buildAllPlatforms();

// --- shadcn-compatible alias layer (maps shadcn var names → our semantic vars) ---
// These reference the semantic vars, which flip under .light automatically.
const shadcn = `
/* shadcn/ui compatible aliases — mapped to design-system semantic tokens. */
/* They reference the semantic vars above, so they re-theme automatically under .light. */
:root {
  --background: var(--color-bg-canvas);
  --foreground: var(--color-text-primary);
  --card: var(--color-bg-subtle);
  --card-foreground: var(--color-text-primary);
  --popover: var(--color-bg-subtle);
  --popover-foreground: var(--color-text-primary);
  --primary: var(--color-brand-primary);
  --primary-foreground: var(--color-brand-on-primary);
  --secondary: var(--color-bg-muted);
  --secondary-foreground: var(--color-text-primary);
  --muted: var(--color-bg-muted);
  --muted-foreground: var(--color-text-secondary);
  --accent: var(--color-accent-default);
  --accent-foreground: var(--color-text-primary);
  --destructive: var(--color-danger-default);
  --destructive-foreground: var(--color-gray-50);
  --border: var(--color-border-default);
  --input: var(--color-border-default);
  --ring: var(--color-border-focus);
  --radius: var(--radius-md);
}
`.trim();

const root = readFileSync('build/css/_root.css', 'utf8');
const light = readFileSync('build/css/_light.css', 'utf8');
const banner = '/* AUTO-GENERATED by token sync (Figma → Style Dictionary). Do not edit. */\n\n';
writeFileSync('build/css/tokens.css', banner + root + '\n' + light + '\n' + shadcn + '\n');

// --- Tailwind preset ---
const tailwind = `// AUTO-GENERATED by token sync. Do not edit.
// Tailwind preset mapping theme tokens to the design-system CSS variables.
module.exports = {
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: { DEFAULT: 'var(--card)', foreground: 'var(--card-foreground)' },
        popover: { DEFAULT: 'var(--popover)', foreground: 'var(--popover-foreground)' },
        primary: { DEFAULT: 'var(--primary)', foreground: 'var(--primary-foreground)' },
        secondary: { DEFAULT: 'var(--secondary)', foreground: 'var(--secondary-foreground)' },
        muted: { DEFAULT: 'var(--muted)', foreground: 'var(--muted-foreground)' },
        accent: { DEFAULT: 'var(--accent)', foreground: 'var(--accent-foreground)' },
        destructive: { DEFAULT: 'var(--destructive)', foreground: 'var(--destructive-foreground)' },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)', md: 'var(--radius-md)', lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)', DEFAULT: 'var(--radius-md)',
      },
      fontFamily: {
        heading: ['Poppins', 'ui-sans-serif', 'sans-serif'],
        body: ['Inter', 'ui-sans-serif', 'sans-serif'],
      },
    },
  },
};
`;
mkdirSync('build/tailwind', { recursive: true });
writeFileSync('build/tailwind/preset.cjs', tailwind);

// --- TypeScript constants (resolved values, both modes) ---
const dark = JSON.parse(readFileSync('build/json/dark.json', 'utf8'));
const lightJson = JSON.parse(readFileSync('build/json/light.json', 'utf8'));
const ts = `// AUTO-GENERATED by token sync (Figma → Style Dictionary). Do not edit.
// Resolved token values. \`tokens\` is the default (dark) theme; \`lightTokens\` is light.
export const tokens = ${JSON.stringify(dark, null, 2)} as const;

export const lightTokens = ${JSON.stringify(lightJson, null, 2)} as const;

export type Tokens = typeof tokens;
`;
mkdirSync('build/ts', { recursive: true });
writeFileSync('build/ts/tokens.ts', ts);

console.log('Token sync build complete: build/css/tokens.css, build/tailwind/preset.cjs, build/ts/tokens.ts');
